// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arypyczzcjpycnzlgyvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyeXB5Y3p6Y2pweWNuemxneXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1OTgwNzEsImV4cCI6MjA4NzE3NDA3MX0.GAOlxekeguI7F9gsQKRh-5IfvXRo-W6FwUipWl7daqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});