// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfxhkkbedmfsfyvmdshg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmeGhra2JlZG1mc2Z5dm1kc2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NDQyOTEsImV4cCI6MjA4NzIyMDI5MX0.xo1J3v56q4LYShsDSSFBW9CT8mCIseKy6rHYxjs9hlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});